# Generated by Django 5.2.1 on 2025-05-11 14:37

import django.db.models.deletion
import xApiCart.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xApiProduct', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(blank=True, default=xApiCart.models.cart_unique_key, help_text='Unique identifier for the cart.', max_length=32, null=True)),
                ('author', models.OneToOneField(help_text='The user who owns this cart.', on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CartItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='The quantity of the product in the cart.')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot price at time of adding to cart', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the cart item is active.')),
                ('uid', models.CharField(blank=True, default=xApiCart.models.cart_item_unique_key, max_length=32, null=True)),
                ('product_id', models.ForeignKey(help_text='The product in this cart item.', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='xApiProduct.productmodel')),
                ('cart_id', models.ForeignKey(help_text='The cart this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='xApiCart.cartmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order_note', models.TextField(blank=True, help_text='Optional notes for the order.', null=True)),
                ('ord_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='The status of the order.', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('shipping_status', models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('is_confirmed', models.BooleanField(default=False, help_text='Indicates if the order is confirmed.')),
                ('uid', models.CharField(blank=True, default=xApiCart.models.order_unique_key, max_length=32, null=True)),
                ('author', models.ForeignKey(help_text='The user who placed this order.', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('cart_id', models.ForeignKey(help_text='The cart associated with this order.', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='xApiCart.cartmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='The quantity of the product in the order.')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='The price of the product at the time of order.', max_digits=10, null=True)),
                ('uid', models.CharField(blank=True, default=xApiCart.models.order_item_unique_key, max_length=32, null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='xApiProduct.productmodel')),
                ('order_id', models.ForeignKey(help_text='The order this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='xApiCart.ordermodel')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'unique_together': {('order_id', 'product_id')},
            },
        ),
    ]
