# Generated by Django 5.2.1 on 2025-05-31 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xApiCart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartmodel',
            options={'ordering': ['-created']},
        ),
    ]
