# Generated by Django 5.2.1 on 2025-05-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xApiCart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='order_num',
            field=models.BigIntegerField(editable=False, unique=True),
        ),
    ]
