# Generated by Django 5.2.1 on 2025-06-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xApiProduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimagemodel',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
