# Generated by Django 5.2.1 on 2025-05-27 12:42

import uuid
import xApiArticle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('cate_name', models.CharField(max_length=512, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uid', models.CharField(default=xApiArticle.models.generate_unique_uid, max_length=32, unique=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=xApiArticle.models.article_image_path)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ArticleMetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=512, null=True)),
                ('meta_desc', models.TextField(blank=True, null=True)),
                ('meta_robots', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('uid', models.CharField(default=xApiArticle.models.generate_unique_uid, max_length=32, unique=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('desc', models.TextField()),
                ('summary', models.TextField(blank=True, help_text='Short summary for preview', null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='article/covers/')),
                ('published_at', models.BooleanField(default=False)),
                ('approve', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('read_time', models.PositiveIntegerField(blank=True, null=True)),
                ('uid', models.CharField(default=xApiArticle.models.generate_unique_uid, max_length=32, unique=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
