# Generated by Django 5.2.1 on 2025-05-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xApiArticle', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemetatag',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
