# Generated by Django 5.2.1 on 2025-06-06 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xApiCart', '0001_initial'),
        ('xApiPayment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalPaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name_of_payer', models.CharField(blank=True, max_length=255, null=True)),
                ('email_of_payer', models.EmailField(blank=True, max_length=254, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('paypal_payment_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('paypal_payer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('paypal_token', models.CharField(blank=True, max_length=255, null=True)),
                ('paypal_payment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_payment', to='xApiCart.ordermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
