# Generated by Django 5.2.1 on 2025-06-24 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsession',
            old_name='user',
            new_name='author',
        ),
    ]
