# Generated by Django 5.2.1 on 2025-05-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xApiPayment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='email_of_payer',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='name_of_payer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
