# Generated by Django 5.2.1 on 2025-05-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xApiProduct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
