# Generated by Django 5.2.1 on 2025-05-30 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xApiProduct', '0002_productmodel_is_approved_productmodel_is_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategorymodel',
            options={'ordering': ['-created']},
        ),
    ]
