# Generated by Django 5.2.1 on 2025-05-21 19:34

import django.db.models.deletion
import uuid
import xApiLedger.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xApiCart', '0002_alter_ordermodel_order_num'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('ent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ent_description', models.TextField(blank=True, max_length=255, null=True)),
                ('ent_num', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('category', models.CharField(choices=[('sales_revenue', 'Sales Revenue'), ('service_revenue', 'Service Revenue'), ('purchases', 'Purchases'), ('rent_expense', 'Rent Expense'), ('salary_payment', 'Salary Payment'), ('utility_bills', 'Utility Bills')], default='sales_revenue', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='posted', max_length=50)),
                ('base_currency', models.CharField(choices=[('BDT', 'Bangladeshi Taka'), ('USD', 'United States Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound Sterling')], default='USD', max_length=10)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=19)),
                ('tax_id', models.CharField(default=xApiLedger.models.tax_id_generator, max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=19)),
                ('debit_amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=19)),
                ('credit_amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=19)),
                ('debit_name', models.CharField(blank=True, max_length=255, null=True)),
                ('credit_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_num', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('ended', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_author', to=settings.AUTH_USER_MODEL)),
                ('ent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='xApiCart.ordermodel')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-created'],
            },
        ),
    ]
